
object Libs {
    const val APPCOMPAT = "androidx.appcompat:appcompat"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout"
    const val MATERIAL = "com.google.android.material:material"
    const val NAVIGATION_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx"
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx"
    const val RETROFIT = "com.squareup.retrofit2:retrofit"
    const val RETROFIT_CONVERTOR_GSON = "com.squareup.retrofit2:converter-gson"
    const val OKHTTP_LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor"
    const val COIL = "io.coil-kt:coil"
    const val TIMBER = "com.jakewharton.timber:timber"
    const val LOGGER = "com.orhanobut:logger:2.2.0"
    const val PREFERENCE = "androidx.preference:preference"
    const val VIEW_MODEL = "androidx.lifecycle:lifecycle-viewmodel-ktx"
    const val LIVE_DATA = "androidx.lifecycle:lifecycle-livedata-ktx"
    const val LIVE_DATA_KAPT = "androidx.lifecycle:lifecycle-compiler"
    const val VIEW_PAGER = "androidx.viewpager2:viewpager2"
    const val RECYCLER_VIEW = "androidx.recyclerview:recyclerview"
    const val GLIDE = "com.github.bumptech.glide:glide"
}